### ISSUE TITLE
Resultado estranho no truncamento.

### ISSUE THREAD

**Issue by MilitaoLucas** [phisgroup/labfis.py#6]
Ao multiplicar por uma constante, o truncamento ficou estranho.
![image](https://user-images.githubusercontent.com/61480539/81853345-afe2c800-9532-11ea-8781-3c8723c02025.png)
Ficou 1.07 ± 0.1. Acredito que o certo seria 1.1 ± 0.1. Não foi nada muito sério, mas o software não deveria fazer truncamento automático?

**Comment by hlouzada** [comment]
Duplicate of #4 
Currently fixed in develop version:
`pip install git+https://github.com/phisgroup/labfis.py@development`
